### ISSUE TITLE
Version 2.2 fails to find webdriver jar

### ISSUE THREAD

**Issue by blacksonic** [mllrsohn/gulp-protractor#102]
With previos version 2.1 it all worked but when i update to version 2.2 i get the following error:

```
/home/blacksonic/workspace/angular2-webpack-es6-starter/node_modules/gulp-protractor/node_modules/protractor/node_modules/q/q.js:155
                throw e;
                ^

Error: Could not find chromedriver at /home/blacksonic/workspace/angular2-webpack-es6-starter/node_modules/gulp-protractor/node_modules/protractor/selenium/chromedriver
    at LocalDriverProvider.addDefaultBinaryLocs_ (/home/blacksonic/workspace/angular2-webpack-es6-starter/node_modules/gulp-protractor/node_modules/protractor/lib/driverProviders/local.js:54:15)
    at LocalDriverProvider.setupEnv (/home/blacksonic/workspace/angular2-webpack-es6-starter/node_modules/gulp-protractor/node_modules/protractor/lib/driverProviders/local.js:71:8)
    at Runner.run (/home/blacksonic/workspace/angular2-webpack-es6-starter/node_modules/gulp-protractor/node_modules/protractor/lib/runner.js:278:31)
    at TaskRunner.run (/home/blacksonic/workspace/angular2-webpack-es6-starter/node_modules/gulp-protractor/node_modules/protractor/lib/taskRunner.js:123:19)
    at createNextTaskRunner (/home/blacksonic/workspace/angular2-webpack-es6-starter/node_modules/gulp-protractor/node_modules/protractor/lib/launcher.js:216:20)
    at /home/blacksonic/workspace/angular2-webpack-es6-starter/node_modules/gulp-protractor/node_modules/protractor/lib/launcher.js:239:7
    at _fulfilled (/home/blacksonic/workspace/angular2-webpack-es6-starter/node_modules/gulp-protractor/node_modules/protractor/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/home/blacksonic/workspace/angular2-webpack-es6-starter/node_modules/gulp-protractor/node_modules/protractor/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/home/blacksonic/workspace/angular2-webpack-es6-starter/node_modules/gulp-protractor/node_modules/protractor/node_modules/q/q.js:796:13)
    at /home/blacksonic/workspace/angular2-webpack-es6-starter/node_modules/gulp-protractor/node_modules/protractor/node_modules/q/q.js:604:44
```

It seems that my config parameter may not be passed down although i pass in ```seleniumServerJar```:

```
exports.config = {
  baseUrl: 'http://localhost:9000/',
  framework: 'jasmine',

  seleniumServerJar: findSeleniumJar(),

  useAllAngular2AppRoots: true
}
```

**Comment by blacksonic** [comment]
seems to be failing when the version of my protractor doesnt match the one required by gulp-protractor

**Comment by blacksonic** [comment]
Here is the repository https://github.com/blacksonic/angular2-es6-starter

**Comment by mattfritz** [comment]
Hmmm, nothing changed with webdriver in the last patch... This error is not indicating the Selenium JAR is missing, it is complaining because it can't find Chromedriver. There are a couple things I can suggest.

You can run the included webdriver update task that will download both Chromedriver and Selenium to the default locations. Then you just have to make that a dependency for your `test-e2e` task:

```js
var webdriver_update = require("gulp-protractor").webdriver_update;
gulp.task('webdriver_update', webdriver_update);
```

Output should look like:

```
[14:28:06] Using gulpfile ~/src/oss/angular2-es6-starter/gulpfile.js
[14:28:06] Starting 'webdriver_update'...
Updating selenium standalone
downloading https://selenium-release.storage.googleapis.com/2.51/selenium-server-standalone-2.51.0.jar...
Updating chromedriver
downloading https://chromedriver.storage.googleapis.com/2.21/chromedriver_mac32.zip...
chromedriver_2.21.zip downloaded to ~/src/oss/angular2-es6-starter/node_modules/protractor/selenium/chromedriver_2.21.zip
selenium-server-standalone-2.51.0.jar downloaded to ~/src/oss/angular2-es6-starter/node_modules/protractor/selenium/selenium-server-standalone-2.51.0.jar
[14:28:25] Finished 'webdriver_update' after 18 s
```

Protractor successfully runs for me on a clone of your repo after adding that task. Can you give that a shot and let me know how it works for you?

**Comment by blacksonic** [comment]
Yes now it runs, but fails if i upgrade protractor to the latest

**Comment by blacksonic** [comment]
The difference is that with current version gulp-protractor's protractor version and my installed one from package.json is the same. If i upgrade protractor it will complain about the version missmatch and the error comes it cant find chromedriver

**Comment by manoj9788** [comment]
Yes I agree with @blacksonic  I use Protractor 3.2.2 latest and the gulp-protractor says it cannot find chrome driver in /node_modules/gulp-protractor/

**Comment by mattfritz** [comment]
Currently gulp-protractor installs Protractor as a dependency instead of a `peerDependency` (see https://github.com/mllrsohn/gulp-protractor/issues/101). Until that change is made, adding a different version of Protractor as an explicit dependency may have unexpected side effects when gulp-protractor searches for binaries. 

I'll update the version tonight to `v3.2.2`, but this problem is caused by installing multiple mismatched versions and is not supported. Let me know if you have any additional information and I'll reopen the issue.
