### ISSUE TITLE
webdriver_update_specific not update

### ISSUE THREAD

**Issue by kamihouse** [mllrsohn/gulp-protractor#142]
Guys, apparently it is not possible update the webdriver using `gulpfile.babel.js`, getting message `No update-config.json found`

I create the task:

```javascript
import {protractor, webdriver_update_specific} from 'gulp-protractor';

const webDriverUpdate = webdriver_update_specific({
  webdriverManagerArgs: ['--ignore_ssl'],
});
```

So running: `./node_modules/gulp/bin/gulp.js webDriverUpdate` results in:

```
[11:32:25] Requiring external module @babel/register
[11:32:26] Using gulpfile /private/tmp/landing-page/gulpfile.babel.js
[11:32:26] Starting 'wdu'...
webdriver-manager: using local installed version 12.1.1
[11:32:27] I/http_utils - ignoring SSL certificate
[11:32:27] I/http_utils - ignoring SSL certificate
[11:32:27] I/http_utils - ignoring SSL certificate
[11:32:27] I/http_utils - ignoring SSL certificate
[11:32:27] I/http_utils - ignoring SSL certificate
[11:32:27] I/http_utils - ignoring SSL certificate
[11:32:27] I/update - chromedriver: file exists /private/tmp/landing-page/node_modules/webdriver-manager/selenium/chromedriver_2.45.zip
[11:32:27] I/update - chromedriver: unzipping chromedriver_2.45.zip
[11:32:27] I/update - chromedriver: setting permissions to 0755 for /private/tmp/landing-page/node_modules/webdriver-manager/selenium/chromedriver_2.45
[11:32:27] I/update - chromedriver: chromedriver_2.45 up to date
[11:32:27] I/update - selenium standalone: file exists /private/tmp/landing-page/node_modules/webdriver-manager/selenium/selenium-server-standalone-3.141.59.jar
[11:32:27] I/update - selenium standalone: selenium-server-standalone-3.141.59.jar up to date
[11:32:29] I/update - geckodriver: file exists /private/tmp/landing-page/node_modules/webdriver-manager/selenium/geckodriver-v0.24.0.tar.gz
[11:32:29] I/update - geckodriver: unzipping geckodriver-v0.24.0.tar.gz
[11:32:29] I/update - geckodriver: setting permissions to 0755 for /private/tmp/landing-page/node_modules/webdriver-manager/selenium/geckodriver-v0.24.0
[11:32:29] I/update - geckodriver: geckodriver-v0.24.0 up to date
[11:32:29] Finished 'wdu' after 2.14 s
```

When run tests: `const test = gulp.series(build, webDriverUpdate, e2e);` results:

```
...
[11:34:57] Starting 'bound wdUpdate'...
webdriver-manager: using local installed version 12.1.1
[11:34:57] I/http_utils - ignoring SSL certificate
[11:34:57] I/http_utils - ignoring SSL certificate
[11:34:57] I/http_utils - ignoring SSL certificate
[11:34:57] I/http_utils - ignoring SSL certificate
[11:34:57] I/http_utils - ignoring SSL certificate
[11:34:57] I/http_utils - ignoring SSL certificate
[11:34:57] I/update - chromedriver: file exists /private/tmp/landing-page/node_modules/webdriver-manager/selenium/chromedriver_2.45.zip
[11:34:57] I/update - chromedriver: unzipping chromedriver_2.45.zip
[11:34:58] I/update - chromedriver: setting permissions to 0755 for /private/tmp/landing-page/node_modules/webdriver-manager/selenium/chromedriver_2.45
[11:34:58] I/update - chromedriver: chromedriver_2.45 up to date
[11:34:58] I/update - selenium standalone: file exists /private/tmp/landing-page/node_modules/webdriver-manager/selenium/selenium-server-standalone-3.141.59.jar
[11:34:58] I/update - selenium standalone: selenium-server-standalone-3.141.59.jar up to date
[11:34:59] I/update - geckodriver: file exists /private/tmp/landing-page/node_modules/webdriver-manager/selenium/geckodriver-v0.24.0.tar.gz
[11:34:59] I/update - geckodriver: unzipping geckodriver-v0.24.0.tar.gz
[11:34:59] I/update - geckodriver: setting permissions to 0755 for /private/tmp/landing-page/node_modules/webdriver-manager/selenium/geckodriver-v0.24.0
[11:34:59] I/update - geckodriver: geckodriver-v0.24.0 up to date
[11:34:59] Finished 'bound wdUpdate' after 2.12 s
[11:34:59] Starting 'e2e'...
[Browsersync] Access URLs:
 ----------------------------------
       Local: http://localhost:3000
    External: http://0.0.0.0:3000
 ----------------------------------
          UI: http://localhost:3001
 UI External: http://localhost:3001
 ----------------------------------
[Browsersync] Serving files from: dist
[11:35:00] E/local - Error code: 135
[11:35:00] E/local - Error message: No update-config.json found. Run 'webdriver-manager update' to download binaries.
[11:35:00] E/local - Error: No update-config.json found. Run 'webdriver-manager update' to download binaries.
    at Local.addDefaultBinaryLocs_ (/private/tmp/landing-page/node_modules/protractor/built/driverProviders/local.js:39:23)
    at Local.setupDriverEnv (/private/tmp/landing-page/node_modules/protractor/built/driverProviders/local.js:105:14)
    at Local.setupEnv (/private/tmp/landing-page/node_modules/protractor/built/driverProviders/driverProvider.js:111:34)
    at q.then (/private/tmp/landing-page/node_modules/protractor/built/runner.js:335:41)
    at _fulfilled (/private/tmp/landing-page/node_modules/protractor/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/private/tmp/landing-page/node_modules/protractor/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/private/tmp/landing-page/node_modules/protractor/node_modules/q/q.js:796:13)
    at /private/tmp/landing-page/node_modules/protractor/node_modules/q/q.js:857:14
    at runSingle (/private/tmp/landing-page/node_modules/protractor/node_modules/q/q.js:137:13)
    at flush (/private/tmp/landing-page/node_modules/protractor/node_modules/q/q.js:125:13)
[11:35:00] E/launcher - Process exited with error code 135
[11:35:00] 'e2e' errored after 1.4 s
[11:35:00] Error in plugin "gulp-protractor"
```

### Workaround

Run `./node_modules/protractor/bin/webdriver-manager update` before test:

```
[11:51:44] I/file_manager - creating folder /private/tmp/landing-page/node_modules/protractor/node_modules/webdriver-manager/selenium
[11:51:44] I/config_source - curl -o/private/tmp/landing-page/node_modules/protractor/node_modules/webdriver-manager/selenium/standalone-response.xml https://selenium-release.storage.googleapis.com/
[11:51:44] I/config_source - curl -o/private/tmp/landing-page/node_modules/protractor/node_modules/webdriver-manager/selenium/chrome-response.xml https://chromedriver.storage.googleapis.com/
[11:51:44] I/config_source - curl -o/private/tmp/landing-page/node_modules/protractor/node_modules/webdriver-manager/selenium/gecko-response.json https://api.github.com/repos/mozilla/geckodriver/releases
[11:51:45] I/downloader - curl -o/private/tmp/landing-page/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_2.45.zip https://chromedriver.storage.googleapis.com/2.45/chromedriver_mac64.zip
[11:51:45] I/downloader - curl -o/private/tmp/landing-page/node_modules/protractor/node_modules/webdriver-manager/selenium/selenium-server-standalone-3.141.59.jar https://selenium-release.storage.googleapis.com/3.141/selenium-server-standalone-3.141.59.jar
[11:51:45] I/update - chromedriver: unzipping chromedriver_2.45.zip
[11:51:46] I/update - chromedriver: setting permissions to 0755 for /private/tmp/landing-page/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_2.45
[11:51:49] I/downloader - curl -o/private/tmp/landing-page/node_modules/protractor/node_modules/webdriver-manager/selenium/geckodriver-v0.24.0.tar.gz https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-macos.tar.gz
[11:51:50] I/update - geckodriver: unzipping geckodriver-v0.24.0.tar.gz
[11:51:51] I/update - geckodriver: setting permissions to 0755 for /private/tmp/landing-page/node_modules/protractor/node_modules/webdriver-manager/selenium/geckodriver-v0.24.0
```

And test:

```
...
[11:53:05] Starting 'bound wdUpdate'...
webdriver-manager: using local installed version 12.1.1
[11:53:06] I/http_utils - ignoring SSL certificate
[11:53:06] I/http_utils - ignoring SSL certificate
[11:53:06] I/http_utils - ignoring SSL certificate
[11:53:06] I/http_utils - ignoring SSL certificate
[11:53:06] I/http_utils - ignoring SSL certificate
[11:53:06] I/http_utils - ignoring SSL certificate
[11:53:06] I/update - chromedriver: file exists /private/tmp/landing-page/node_modules/webdriver-manager/selenium/chromedriver_2.45.zip
[11:53:06] I/update - chromedriver: unzipping chromedriver_2.45.zip
[11:53:07] I/update - chromedriver: setting permissions to 0755 for /private/tmp/landing-page/node_modules/webdriver-manager/selenium/chromedriver_2.45
[11:53:07] I/update - chromedriver: chromedriver_2.45 up to date
[11:53:07] I/update - selenium standalone: file exists /private/tmp/landing-page/node_modules/webdriver-manager/selenium/selenium-server-standalone-3.141.59.jar
[11:53:07] I/update - selenium standalone: selenium-server-standalone-3.141.59.jar up to date
[11:53:08] I/update - geckodriver: file exists /private/tmp/landing-page/node_modules/webdriver-manager/selenium/geckodriver-v0.24.0.tar.gz
[11:53:08] I/update - geckodriver: unzipping geckodriver-v0.24.0.tar.gz
[11:53:08] I/update - geckodriver: setting permissions to 0755 for /private/tmp/landing-page/node_modules/webdriver-manager/selenium/geckodriver-v0.24.0
[11:53:08] I/update - geckodriver: geckodriver-v0.24.0 up to date
[11:53:08] Finished 'bound wdUpdate' after 3.11 s
[11:53:08] Starting 'e2e'...
[Browsersync] Access URLs:
 ---------------------------------------
       Local: http://localhost:3000
    External: http://192.168.40.202:3000
 ---------------------------------------
          UI: http://localhost:3001
 UI External: http://localhost:3001
 ---------------------------------------
[Browsersync] Serving files from: dist
Started
Jasmine started
.
  E2E: Auth
    ✓ Deve conter "Bem vindo" na tag de título

1 spec, 0 failures
Finished in 0.702 seconds

Executed 1 of 1 spec SUCCESS in 0.701 sec.
[11:53:13] Finished 'e2e' after 5.16 s
[11:53:13] Finished 'test' after 9.84 s
```

**Comment by nathando** [comment]
Do you guys know what's wrong yet ? Just encountered the same issue.
