### ISSUE TITLE
Selenium not found

### ISSUE THREAD

**Issue by calebthebrewer** [mllrsohn/gulp-protractor#44]
[Protractor](https://github.com/angular/protractor/releases) was update a couple days ago and it appears to have broken the build of this component. Now when I install this component the protractor it installs does not have the selenium standalone located in the correct directory, (protractor now uses a newer version of selenium).

I have reverted to running protractor via a child process until this has been resolved:

```js
gulp.task("e2e-test", ["server"], function(done) {
	exec("protractor protractor.conf.js", function(err, stdout) {
		console.log(stdout);
		connect.serverClose();
		done();
	});
});
```
This requires `npm install protractor` and `webdriver-manager update` to be run as well.

**Comment by mavdi** [comment]
You can install it by 

```
./node_modules/protractor/bin/webdriver-manager update
```

but I still can't get it to work using this jar...

**Comment by eranimo** [comment]
This problem still exists. The above solution did not work for me either. Is there any word on why/when this will be fixed?

**Comment by RobbinHabermehl** [comment]
What if you remove the `node_modules` directory and run a fresh `npm install`?

**Comment by bvaughn** [comment]
Still happening, even for fresh installs.

**Comment by jmsherry** [comment]
+1

**Comment by RyanWarner** [comment]
+1

**Comment by RyanWarner** [comment]
I solved this by installing selenium-standalone-jar
```
npm install selenium-standalone-jar --save-dev
```
And setting the path in my protractor.config.js to
```
seleniumServerJar: '../node_modules/selenium-standalone-jar/bin/selenium-server-standalone-2.45.0.jar'
```
See #56

**Comment by sambernet** [comment]
Even easier is to just require selenium-standalone-jar in your conf.js and then use the exported .path property:

```js
import seleniumServerJar = require("selenium-standalone-jar");
```
And in the config block:
```js
  seleniumServerJar = seleniumServerJar.path;
```

**Comment by mattfritz** [comment]
I believe this was an issue with a previous protractor release, namely with `webdriver-manager`. Let me know if this exact issue is still a thing.

**Comment by phaldiya** [comment]
gulp-protractor not able to find **selenium-server-standalone** at `/node_modules/gulp-protractor/node_modules/protractor/node_modules/webdriver-manager/selenium/selenium-server-standalone-2.53.1.jar`

I think it should look into protractor library for selenium-server, but it's not; correct me if I am wrong. 

I am using following versions
"protractor": "^5.1.1",
"gulp-protractor": "3.0.0"

Error stacktrace

```
[08:25:51] E/local - Error code: 135
[08:25:51] E/local - Error message: No selenium server jar found at /Users/pradeeph/Documents/workspace/t2/inspect/node_modules/gulp-protractor/node_modules/protractor/node_modules/webdriver-manager/selenium/selenium-server-standalone-2.53.1.jar. Run 'webdriver-manager update' to download binaries.
[08:25:51] E/local - Error: No selenium server jar found at /Users/pradeeph/Documents/workspace/t2/inspect/node_modules/gulp-protractor/node_modules/protractor/node_modules/webdriver-manager/selenium/selenium-server-standalone-2.53.1.jar. Run 'webdriver-manager update' to download binaries.
    at BrowserError.IError [as constructor] (/Users/pradeeph/Documents/workspace/t2/inspect/node_modules/gulp-protractor/node_modules/protractor/built/exitCodes.js:13:23)
    at BrowserError.ProtractorError [as constructor] (/Users/pradeeph/Documents/workspace/t2/inspect/node_modules/gulp-protractor/node_modules/protractor/built/exitCodes.js:21:28)
    at new BrowserError (/Users/pradeeph/Documents/workspace/t2/inspect/node_modules/gulp-protractor/node_modules/protractor/built/exitCodes.js:67:23)
    at Local.addDefaultBinaryLocs_ (/Users/pradeeph/Documents/workspace/t2/inspect/node_modules/gulp-protractor/node_modules/protractor/built/driverProviders/local.js:44:19)
    at Local.setupEnv (/Users/pradeeph/Documents/workspace/t2/inspect/node_modules/gulp-protractor/node_modules/protractor/built/driverProviders/local.js:74:14)
    at Runner.run (/Users/pradeeph/Documents/workspace/t2/inspect/node_modules/gulp-protractor/node_modules/protractor/built/runner.js:274:37)
    at TaskRunner.run (/Users/pradeeph/Documents/workspace/t2/inspect/node_modules/gulp-protractor/node_modules/protractor/built/taskRunner.js:116:27)
    at createNextTaskRunner (/Users/pradeeph/Documents/workspace/t2/inspect/node_modules/gulp-protractor/node_modules/protractor/built/launcher.js:228:28)
    at /Users/pradeeph/Documents/workspace/t2/inspect/node_modules/gulp-protractor/node_modules/protractor/built/launcher.js:253:13
    at _fulfilled (/Users/pradeeph/Documents/workspace/t2/inspect/node_modules/q/q.js:834:54)
[08:25:51] E/launcher - Process exited with error code 135
[08:25:51] 'e2e:internal' errored after 902 ms
[08:25:51] Error in plugin 'gulp-protractor'
Message:
    protractor exited with code 135
{ [Error: protractor exited with code 135]
  message: 'protractor exited with code 135',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-protractor',
  __safety: { toString: [Function: bound ] } }
[08:25:51] Error in plugin 'run-sequence(e2e:internal)'
Error
    at finish (/Users/pradeeph/Documents/workspace/t2/inspect/node_modules/run-sequence/index.js:56:13)
    at Gulp.onError (/Users/pradeeph/Documents/workspace/t2/inspect/node_modules/run-sequence/index.js:67:4)
    at emitOne (events.js:101:20)
    at Gulp.emit (events.js:189:7)
    at Gulp.Orchestrator._emitTaskDone (/Users/pradeeph/Documents/workspace/t2/inspect/node_modules/orchestrator/index.js:264:8)
    at /Users/pradeeph/Documents/workspace/t2/inspect/node_modules/orchestrator/index.js:275:23
    at finish (/Users/pradeeph/Documents/workspace/t2/inspect/node_modules/orchestrator/lib/runTask.js:21:8)
    at Stream.<anonymous> (/Users/pradeeph/Documents/workspace/t2/inspect/node_modules/orchestrator/lib/runTask.js:52:4)
    at Stream.f (/Users/pradeeph/Documents/workspace/t2/inspect/node_modules/end-of-stream/node_modules/once/once.js:17:25)
    at emitOne (events.js:101:20)

Process finished with exit code 1

```
