### ISSUE TITLE
Getting ENOENT error on Windows when using Gulp Protractor

### ISSUE THREAD

**Issue by JamesBender** [mllrsohn/gulp-protractor#50]
Used Yeoman to generate an app with the Angular Gulp generator, getting this

$ gulp protractor
[16:34:45] Using gulpfile d:\Github\AngularMusicStoredotNet\FrontEnd\gulpfile.js
[16:34:45] Starting 'wiredep'...
[16:34:45] Starting 'scripts'...
[16:34:46] Starting 'injector:css:preprocessor'...
[16:34:46] Starting 'webdriver-update'...
[16:34:46] gulp-inject Nothing to inject into index.scss.
[16:34:46] Finished 'wiredep' after 1.09 s
[16:34:46] Finished 'injector:css:preprocessor' after 621 ms
[16:34:46] Starting 'styles'...
selenium standalone is up to date.
chromedriver is up to date.
[16:34:47] Finished 'webdriver-update' after 628 ms
[16:34:47] Finished 'scripts' after 1.53 s
[16:34:47] Finished 'styles' after 1.16 s
[16:34:47] Starting 'injector:css'...
[16:34:47] gulp-inject 1 files into index.html.
[16:34:47] Finished 'injector:css' after 9.19 ms
[16:34:47] Starting 'injector:js'...
[16:34:48] gulp-inject 3 files into index.html.
[16:34:48] Finished 'injector:js' after 430 ms
[16:34:48] Starting 'serve:e2e'...
[16:34:48] Finished 'serve:e2e' after 173 ms
[16:34:48] Starting 'protractor:src'...
Starting selenium standalone server...
[launcher] Running 1 instances of WebDriver
[launcher] Process exited with error code 1

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)

d:\Github\AngularMusicStoredotNet\FrontEnd\gulp\e2e-tests.js:25
      throw err;
            ^
Error: protractor exited with code 8

Already looked here, https://github.com/mllrsohn/gulp-protractor/issues/10 and it looks like I'm having the same issue and was able to run the tests from the Git repo mentioned, but not sure what to do next.

Thanks,

**Comment by JamesBender** [comment]
Never mind. Turned out Java didn't get installed on the machine in question.
