### ISSUE TITLE
Error: Promise has no method 'match'

### ISSUE THREAD

**Issue by alias1** [mllrsohn/gulp-protractor#62]
Getting the following error from my tests. I'm pretty sure it's an error in the test itself, but the stacktrace doesn't really indicate where/how/why. It looks as though this is an issue in jasmine maybe..? But was wondering if there is something that can be added/fixed here, or a request sent upstream to get a useful stacktrace?

```
/Users/alias/dev/foo/node_modules/gulp-protractor/node_modules/protractor/node_modules/jasminewd/index.js:277
        if (failureItem.toString().match(jasmineTimeoutRegexp)) {

                                   ^
TypeError: Object Promise::10075 {[[PromiseStatus]]: "fulfilled"} has no method 'match'
    at [object Object].OnTimeoutReporter.reportSpecResults (/Users/alias/dev/foo/node_modules/gulp-protractor/node_modules/protractor/node_modules/jasminewd/index.js:277:36)
    at [object Object].jasmine.NestedResults.totalCount [as reportSpecResults] (/Users/alias/dev/foo/node_modules/gulp-protractor/node_modules/protractor/node_modules/minijasminenode/lib/jasmine-1.3.1.js:1901:39)
    at [object Object].jasmine.Spec.finishCallback (/Users/alias/dev/foo/node_modules/gulp-protractor/node_modules/protractor/node_modules/minijasminenode/lib/jasmine-1.3.1.js:2470:21)
    at [object Object].jasmine.Spec.finish (/Users/alias/dev/foo/node_modules/gulp-protractor/node_modules/protractor/node_modules/minijasminenode/lib/jasmine-1.3.1.js:2475:8)
    at [object Object].onComplete (/Users/alias/dev/foo/node_modules/gulp-protractor/node_modules/protractor/node_modules/minijasminenode/lib/jasmine-1.3.1.js:2504:10)
    at [object Object].jasmine.Queue.next_ (/Users/alias/dev/foo/node_modules/gulp-protractor/node_modules/protractor/node_modules/minijasminenode/lib/jasmine-1.3.1.js:2219:14)
    at [object Object]._onTimeout (/Users/alias/dev/foo/node_modules/gulp-protractor/node_modules/protractor/node_modules/minijasminenode/lib/jasmine-1.3.1.js:2199:18)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
[launcher] Process exited with error code 1
```

Related?
* https://github.com/angular/jasminewd/issues/15
* https://github.com/jasmine/jasmine/issues/734

**Comment by mattfritz** [comment]
This is definitely an issue with Jasmine failures not being reported correctly. Is this still an issue?

I'm going to close this issue, feel free to comment if you have more information.
