### ISSUE TITLE
Running 'gulp protractor-run' doesn't run

### ISSUE THREAD

**Issue by iamryandrake** [mllrsohn/gulp-protractor#78]
When I run ```gulp protractor-run```, I get the following:

```
[16:10:04] Using gulpfile ~/Documents/OtherLevels/portal-plusone/gulpfile.js
[16:10:04] Starting 'protractor-run'...
**you must either specify a configuration file or at least 3 options. See below for the options:

Usage: protractor [configFile] [options]
configFile defaults to protractor.conf.js
The [options] object will override values from the config file.
See the reference config for a full list of options.

Options:
  --help                                             Print Protractor help menu                               
  --version                                          Print Protractor version                                 
  --browser, --capabilities.browserName              Browsername, e.g. chrome or firefox                      
  --seleniumAddress                                  A running selenium address to use                        
  --seleniumServerJar                                Location of the standalone selenium jar file             
  --seleniumPort                                     Optional port for the selenium standalone server         
  --baseUrl                                          URL to prepend to all relative paths                     
  --rootElement                                      Element housing ng-app, if not html or body              
  --specs                                            Comma-separated list of files to test                    
  --exclude                                          Comma-separated list of files to exclude                 
  --verbose, --jasmineNodeOpts.isVerbose             Print full spec names                                    
  --stackTrace, --jasmineNodeOpts.includeStackTrace  Print stack trace on error                               
  --params                                           Param object to be passed to the tests                   
  --framework                                        Test framework to use: jasmine, cucumber or mocha        
  --resultJsonOutputFile                             Path to save JSON test result                            
  --troubleshoot                                     Turn on troubleshooting output                           
  --elementExplorer                                  Interactively test Protractor commands                   
  --debuggerServerPort                               Start a debugger server at specified port instead of repl

[16:10:04] 'protractor-run' errored after 93 ms
[16:10:04] Error: 1
  at formatError (/usr/local/lib/node_modules/gulp/bin/gulp.js:169:10)
  at Gulp.<anonymous> (/usr/local/lib/node_modules/gulp/bin/gulp.js:195:15)
  at Gulp.emit (events.js:107:17)
  at Gulp.Orchestrator._emitTaskDone (/Users/ryandrake/Documents/OtherLevels/portal-plusone/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
  at /Users/ryandrake/Documents/OtherLevels/portal-plusone/node_modules/gulp/node_modules/orchestrator/index.js:275:23
  at finish (/Users/ryandrake/Documents/OtherLevels/portal-plusone/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
  at ChildProcess.cb (/Users/ryandrake/Documents/OtherLevels/portal-plusone/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
  at ChildProcess.g (events.js:199:16)
  at ChildProcess.emit (events.js:110:17)
  at maybeClose (child_process.js:1008:16)
  at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
```

I'm wondering what part of config/setup am I missing? Your README isn't helpful in this case.

**Comment by jameslawson** [comment]
Did you create a **protractor config file** (test/protractor.config.js)?
See 'Configuration' at https://angular.github.io/protractor/
