### ISSUE TITLE
Harmony Selenium

### ISSUE THREAD

**Issue by MilknCookie** [mllrsohn/gulp-protractor#96]
Hi,

Here is the stack trace 
[launcher] Process exited with error code 1
undefined:1190
    vlog(2, () => this + ' scheduling notifications', this);
             ^
SyntaxError: Unexpected token )
    at goog.loadModuleFromSource_ (D:\htdocs\gagal06\tb\NonInventaire\node_modules\selenium-webdriver\lib\goog\base.js:1123:19)
    at Object.goog.loadModule (D:\htdocs\gagal06\tb\NonInventaire\node_modules\selenium-webdriver\lib\goog\base.js:1085:46)
    at D:\htdocs\gagal06\tb\NonInventaire\node_modules\selenium-webdriver\lib\webdriver\promise.js:1:6
    at Object.exports.runInContext (vm.js:64:17)
    at Object.Context.closure.goog.retrieveAndExecModule_ (D:\htdocs\gagal06\tb\NonInventaire\node_modules\selenium-webdriver\_base.js:135:8)
    at <anonymous>:1:6
    at Object.exports.runInContext (vm.js:64:17)
    at Context.closure.closure.vm.createContext.CLOSURE_IMPORT_SCRIPT (D:\htdocs\gagal06\tb\NonInventaire\node_modules\selenium-webdriver\_base.js:104
:12)
    at Object.goog.importScript_ (D:\htdocs\gagal06\tb\NonInventaire\node_modules\selenium-webdriver\lib\goog\base.js:879:9)
    at Object.goog.importModule_ (D:\htdocs\gagal06\tb\NonInventaire\node_modules\selenium-webdriver\lib\goog\base.js:900:14)
{ [Error: protractor exited with code 1]
  message: 'protractor exited with code 1',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-protractor',
  __safety: { toString: [Function] } }
[15:23:43] Finished 'test-protractor' after 2.13 s

Node -v  = 5.7.0
Selenium version = 2.52.0

Related : https://github.com/SeleniumHQ/selenium/issues/1286

Code  

gulp.task('test-protractor', 'runs test', function(cb) {
	gulp.src(['./server/test/protractor/*.js'], { read:false })
		.pipe(gulpProtractor.protractor({
			configFile: './server/test/protractor.config.js',
			args: ['--baseUrl', 'www.realUrlHere.com']
		})).on('error', function(e) {
			if(isCI) {
				throw e;
			} else {
				console.log(e);
			}
			cb();
		}).on('end', function() {
			cb();
		});
});

I have literally spent my day on this. If you have any clue, let me know. I am looking for a way to use the harmony flag somewhere, but so far it ain't working. This is most likely not an issu with gulp-protractor itselft but i believe it could be part of the solution.

Thank you

Edit : windows server 2008 R2 64bits

Edit 2 : im able to start the test in the folder using -> protractor protractor.config.js or  ./test/protractor protractor.config.js

Edit 3 : however i am NOT able to do -> protractor ./server/test/protractor protractor.config.js in the root folder.

**Comment by akizotov** [comment]
Did you ever end up solving this issue?

**Comment by mattfritz** [comment]
@akizotov for reference, this error comes from running on an old version of node.js without harmony support. You can either upgrade node to `>= 4.x` or use the `--harmony` flag on older versions.
